### ISSUE TITLE
Format description is wrong

### ISSUE THREAD

**Issue by Rizhiy** [icevision/annotations#1]
https://github.com/icevision/annotations/blob/91e31d91943dae79fba2e927f32f2b500e83c466/README.md#L12

This is clearly wrong as can be seen by any annotations file, for example `000205.tsv`:
```
class	xtl	ytl	xbr	ybr	temporary	occluded	data
3.2	702	979	730	994	false	true	
2.4	16	946	26	975	false	false	
4.1.2	23	948	32	975	false	false	
```
The relationship is reversed, `br` is always bigger than `tl`.

**Comment by newpavlov** [comment]
Yes, you right. Thank you for noticing!
