### ISSUE TITLE
what's the rule of matching between .flif and .tsv?

### ISSUE THREAD

**Issue by sergorl** [icevision/annotations#2]
I downloaded .flif files of pictures from this: http://oscar.skoltech.ru/data/2018-02-16_1515/
I downloaded .tsv files of annotations from this: https://github.com/icevision/annotations/tree/master/2018-02-16_1515_left

And now I don't understand: what's the rule of matching between .flif and .tsv?

**Comment by newpavlov** [comment]
TSV file name is a position of the frame in the archive. For `2018-02-16_1515//left.tar` the matching for first 3 frames is:
```
1518794153619000_2344689000.flif    000000
1518794153653000_2344722000.flif    000001
1518794153687000_2344756000.flif    000002
```

I recommend to use `convert` utility which can be downloaded from [here](https://github.com/SkoltechRobotics/oscar-cli/releases), it will handle the renaming and conversion into format of your choosing. You can use it like this:
```
$ ./convert mono --histeq -d -f png http://oscar.skoltech.ru/data/2018-02-16_1515/left.tar /path/to/output/folder
```

**Comment by sergorl** [comment]
@newpavlov, can I convert to .png only one .flif file?

**Comment by newpavlov** [comment]
You can stop `convert` at any moment (e.g. after it converted several frames), it also supports `-n` argument which allows you to skip frames (see `convert mono --help`).

**Comment by sergorl** [comment]
@newpavlov, thanks for your help!
